version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./eventcalendar/:/usr/src/app/
    env_file:
      - ./.env.dev
    ports:
      - "8000:8000"
    depends_on:
      - db

  # celery:
  #   build: .
  #   command: bash -c "celery -A eventcalendar worker -l INFO"
  #   environment:
  #     - DEBUG=1
  #     - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1]
  #     - CELERY_BROKER=redis://redis:6379/0
  #     - CELERY_BACKEND=redis://redis:6379/0
  #   depends_on:
  #     - django
  #     - redis

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=AcOMs

  # redis:
  #   image: "redis:alpine"
    # volumes:
    #   - ./redis-data:/data

  # nginx:
  #   build: ./nginx
  #   ports:
  #     - 1337:80
  #   depends_on:
  #     - web
volumes:
  postgres_data: