version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c "python manage.py flush --no-input && python manage.py migrate && python manage.py dbshell < data.sql && python manage.py collectstatic --noinput && gunicorn eventcalendar.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
      
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:80
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
  media_volume:
