# Generated by Django 3.2.14 on 2023-07-10 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_carrera', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='CarreraAlumno',
            fields=[
                ('id_carrera_alumno', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Carreras Alumno',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_departamento', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_facultad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_facultad', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Facultades',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=30, unique=True)),
                ('correo', models.CharField(blank=True, max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('celular', models.CharField(blank=True, max_length=30)),
                ('carrera_alumno', models.ManyToManyField(blank=True, help_text='Las carreras asignadas al alumno', related_name='alumno_carrera', through='accounts.CarreraAlumno', to='accounts.Carrera')),
            ],
            options={
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_tipo_documento', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de documento',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='alumno', serialize=False, to='accounts.persona')),
            ],
            options={
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='FuncionarioDocente',
            fields=[
                ('id_funcionario_docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='funcionario_docente', serialize=False, to='accounts.persona')),
            ],
            options={
                'verbose_name_plural': 'Funcionarios/Docentes',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='id_tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_documento', to='accounts.tipodocumento'),
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_materia', models.CharField(max_length=100)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materia_departameto', to='accounts.departamento')),
            ],
            options={
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='id_facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamento_facultad', to='accounts.facultad'),
        ),
        migrations.AddField(
            model_name='carreraalumno',
            name='id_alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno_carrera', to='accounts.persona'),
        ),
        migrations.AddField(
            model_name='carreraalumno',
            name='id_carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrera_alumno', to='accounts.carrera'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='id_facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carrera_facultad', to='accounts.facultad'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('documento', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('email', models.EmailField(help_text='Ex: example@example.com', max_length=255, unique=True, verbose_name='Email Address')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('id_persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to='accounts.persona')),
                ('materia_func_doc', models.ManyToManyField(blank=True, help_text='Las materias asignadas al Funcionario/Docente', related_name='func_doc_materias', to='accounts.Materia')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='docente', serialize=False, to='accounts.funcionariodocente')),
            ],
            options={
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='funcionario', serialize=False, to='accounts.funcionariodocente')),
            ],
            options={
                'verbose_name_plural': 'Funcionarios',
            },
        ),
    ]
