# Generated by Django 3.2.14 on 2023-03-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factultad',
            fields=[
                ('id_facultad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_facultad', models.CharField(max_length=60)),
            ],
        ),
    ]
