# Generated by Django 3.2.14 on 2023-03-28 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_factultad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Factultad',
            new_name='Facultad',
        ),
    ]
