# Generated by Django 3.2.14 on 2023-09-05 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230904_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 9, 5, 11, 34, 54, 223003)),
        ),
    ]
