# Generated by Django 3.2.14 on 2023-04-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_factultad_facultad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_carrera', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_departamento', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_materia', models.CharField(max_length=60)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materia_departameto', to='accounts.departamento')),
            ],
            options={
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.AlterModelOptions(
            name='facultad',
            options={'verbose_name_plural': 'Facultades'},
        ),
        migrations.CreateModel(
            name='MateriaFuncionarioDocente',
            fields=[
                ('id_materia_funcionario_docente', models.AutoField(primary_key=True, serialize=False)),
                ('id_funcionario_docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionario_docente_materia', to='accounts.funcionariodocente')),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materia_funcionario_docente', to='accounts.materia')),
            ],
            options={
                'verbose_name_plural': 'Materias Funcionario/Docente',
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='id_facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamento_facultad', to='accounts.facultad'),
        ),
        migrations.CreateModel(
            name='CarreraAlumno',
            fields=[
                ('id_carrera_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumno_carrera', to='accounts.alumno')),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carrera_alumno', to='accounts.carrera')),
            ],
            options={
                'verbose_name_plural': 'Carreras Alumno',
            },
        ),
        migrations.AddField(
            model_name='carrera',
            name='id_facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carrera_facultad', to='accounts.facultad'),
        ),
    ]
