# Generated by Django 3.2.14 on 2023-04-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230411_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='descripcion_carrera',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='descripcion_departamento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='materia',
            name='descripcion_materia',
            field=models.CharField(max_length=100),
        ),
    ]
