# Generated by Django 3.2.14 on 2023-09-05 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_post_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 9, 5, 22, 2, 13, 697476)),
        ),
    ]
