# Generated by Django 3.2.14 on 2023-10-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_post_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
