# Generated by Django 3.2.14 on 2023-07-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='detalleactividadacademica',
            name='unicos_participantes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='id_persona_receptor',
        ),
        migrations.RemoveField(
            model_name='event',
            name='participante_acti_academ',
        ),
        migrations.AlterField(
            model_name='cita',
            name='es_notificable',
            field=models.BooleanField(default=True),
        ),
    ]
