# Generated by Django 3.2.14 on 2023-10-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientacionacademica',
            name='motivo_cancelacion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tutoria',
            name='motivo_cancelacion',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
