# Generated by Django 3.2.14 on 2023-03-14 20:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):


    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id_convocatoria', models.AutoField(primary_key=True, serialize=False)),
                ('anho', models.IntegerField(validators=[django.core.validators.MinValueValidator(2023)])),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id_dia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_dia', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id_semestre', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_semestre', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioSemestral',
            fields=[
                ('id_horario_semestral', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('id_convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convocatoria_calendario', to='calendarapp.convocatoria')),
                ('id_dia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hsem_dia', to='calendarapp.dia')),
                ('id_funcionario_docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='func_doc_calendario', to='accounts.funcionariodocente')),
            ],
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='id_semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semestre_calendario', to='calendarapp.semestre'),
        ),
        migrations.AddConstraint(
            model_name='horariosemestral',
            constraint=models.UniqueConstraint(fields=('id_funcionario_docente', 'id_convocatoria', 'id_dia', 'hora_inicio', 'hora_fin'), name='unique_horario_semestral'),
        ),
    ]
