# Generated by Django 3.2.14 on 2023-11-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_auto_20231024_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('iniciar_cita', 'Iniciar cita'), ('finalizar_cita', 'Finalizar cita'), ('editar_cita', 'Editar cita'), ('cancelar_cita', 'Cancelar cita'), ('confirmar_cita', 'Confirmar cita'), ('registrar_cita', 'registar cita'), ('rechazar_cita', 'rechazar cita'), ('editar_actividad_academica', 'Editar Actividad Academica'), ('registrar_actividad_academica', 'Registrar Actividad Academica'), ('cancelar_actividad_academica', 'Cancelar Actividad Academica'), ('finalizar_actividad_academica', 'Finalizar Actividad Academica')], 'verbose_name_plural': 'Actividades Academicas'},
        ),
    ]
