# Generated by Django 3.2.14 on 2023-07-15 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_auto_20230715_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleactividadacademica',
            name='es_alumno',
        ),
        migrations.RemoveField(
            model_name='detalleactividadacademica',
            name='es_docente',
        ),
        migrations.RemoveField(
            model_name='detalleactividadacademica',
            name='es_funcionario',
        ),
    ]
