# Generated by Django 3.2.14 on 2023-07-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_auto_20230715_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='motivo_cancelacion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='motivo_rechazo',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
