# Generated by Django 3.2.14 on 2024-01-25 15:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20231110_1422'),
        ('calendarapp', '0003_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='anho',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2024)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='id_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departamento', to='accounts.departamento'),
        ),
    ]
