# Generated by Django 3.2.14 on 2023-08-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_auto_20230726_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime_registro',
            field=models.DateTimeField(),
        ),
    ]
