# Generated by Django 3.2.14 on 2023-04-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_remove_horariosemestral_unique_horario_semestral'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horariosemestral',
            options={'verbose_name_plural': 'Horarios Semestrales'},
        ),
    ]
