# Generated by Django 3.2.14 on 2023-04-21 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230421_1454'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarapp', '0005_alter_horariosemestral_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoActividadAcademica',
            fields=[
                ('id_estado_actividad_academica', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_estado_actividad_academica', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTarea',
            fields=[
                ('id_estado_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_estado_tarea', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id_actividad_academica', models.AutoField(primary_key=True, serialize=False)),
                ('datetime_inicio_estimado', models.DateTimeField()),
                ('datetime_fin_estimado', models.DateTimeField()),
                ('datetime_inicio_real', models.DateTimeField(default=None, null=True)),
                ('datetime_fin_real', models.DateTimeField(default=None, null=True)),
                ('datetime_registro', models.DateTimeField(auto_now=True)),
                ('observacion', models.CharField(max_length=500, null=True)),
                ('nro_curso', models.CharField(max_length=30, null=True)),
                ('id_convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convocatoria', to='calendarapp.convocatoria')),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamento', to='accounts.departamento')),
                ('id_estado_actividad_academica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado_acti_aca', to='calendarapp.estadoactividadacademica')),
                ('id_facultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facultad', to='accounts.facultad')),
                ('id_funcionario_docente_encargado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionario_docente_encarcado', to='accounts.funcionariodocente')),
                ('id_materia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materia', to='accounts.materia')),
                ('id_persona_alta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persona_alta', to='accounts.persona')),
                ('id_persona_receptor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persona_receptor', to='accounts.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id_motivo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_motivo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOrientacionAcademica',
            fields=[
                ('id_tipo_orientacion_academica', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_tipo_orientacion_academica', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTarea',
            fields=[
                ('id_tipo_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_tipo_tarea', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTutoria',
            fields=[
                ('id_tipo_tutoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_tipo_tutoria', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id_unidad_medida', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_unidad_medida', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='ori_academ_cita', serialize=False, to='calendarapp.event')),
                ('es_tutoria', models.BooleanField(default=False)),
                ('es_orientacion_academica', models.BooleanField(default=False)),
                ('es_notificable', models.BooleanField(default=False)),
                ('motivo', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrientacionAcademica',
            fields=[
                ('id_orientacion_academica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='acti_academ_orient_academ', serialize=False, to='calendarapp.event')),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id_parametro', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_parametro', models.CharField(max_length=50, null=True)),
                ('valor', models.IntegerField()),
                ('es_orientacion_academica', models.BooleanField(default=False)),
                ('es_tutoria', models.BooleanField(default=False)),
                ('id_unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidad_medida_parametro', to='calendarapp.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id_actividad_academica', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendarapp.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleActividadAcademica',
            fields=[
                ('id_detalle_actividad_Academica', models.AutoField(primary_key=True, serialize=False)),
                ('es_docente', models.BooleanField(default=False)),
                ('es_funcionario', models.BooleanField(default=False)),
                ('es_alumno', models.BooleanField(default=False)),
                ('id_actividad_academica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividad_academica', to='calendarapp.event')),
                ('id_participante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persona_participante', to='accounts.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('id_tutoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='acri_academ_tutoria', serialize=False, to='calendarapp.event')),
                ('nombre_trabajo', models.CharField(max_length=200, null=True)),
                ('id_cita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutoria_cita', to='calendarapp.cita')),
                ('id_tipo_tutoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_tutoria', to='calendarapp.tipotutoria')),
            ],
        ),
        migrations.AddConstraint(
            model_name='parametro',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('es_orientacion_academica', False), ('es_tutoria', True)), models.Q(('es_orientacion_academica', True), ('es_tutoria', False)), _connector='OR'), name='solo_uno_puede_ser_true'),
        ),
        migrations.AddField(
            model_name='orientacionacademica',
            name='id_cita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita_ori_academ', to='calendarapp.cita'),
        ),
        migrations.AddField(
            model_name='orientacionacademica',
            name='id_motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motivo_ori_academ', to='calendarapp.motivo'),
        ),
        migrations.AddField(
            model_name='orientacionacademica',
            name='id_tipo_orientacion_academica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_ori_academ', to='calendarapp.tipoorientacionacademica'),
        ),
        migrations.AlterUniqueTogether(
            name='eventmember',
            unique_together={('event', 'user')},
        ),
        migrations.AddConstraint(
            model_name='detalleactividadacademica',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('es_alumno', False), ('es_docente', True), ('es_funcionario', False)), models.Q(('es_alumno', False), ('es_docente', False), ('es_funcionario', True)), models.Q(('es_alumno', True), ('es_docente', False), ('es_funcionario', False)), _connector='OR'), name='unicos_participantes'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_parametro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parametro_cita', to='calendarapp.parametro'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('es_orientacion_academica', False), ('es_tutoria', True)), models.Q(('es_orientacion_academica', True), ('es_tutoria', False)), _connector='OR'), name='unicos_cita'),
        ),
    ]
