# Generated by Django 3.2.14 on 2023-08-08 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('calendarapp', '0005_alter_event_datetime_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='id_persona_solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.persona'),
        ),
    ]
