# Generated by Django 3.2.14 on 2023-05-16 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0006_auto_20230421_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivo',
            name='id_tipo_orientacion_academica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motivo_orientacion_academica', to='calendarapp.tipoorientacionacademica'),
        ),
    ]
