# Generated by Django 3.2.14 on 2023-08-10 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('calendarapp', '0006_event_id_persona_solicitante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('datetime_inicio_estimado', models.DateTimeField(null=True)),
                ('datetime_inicio_real', models.DateTimeField(null=True)),
                ('datetime_vencimiento', models.DateTimeField(null=True)),
                ('datetime_alta', models.DateTimeField()),
                ('datetime_finalizacion', models.DateTimeField(null=True)),
                ('datetime_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('observacion', models.CharField(max_length=500)),
                ('es_notificable', models.BooleanField(default=True)),
                ('id_estado_tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarea_estado', to='calendarapp.estadotarea')),
                ('id_orientacion_academica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarea_ori_academ', to='calendarapp.orientacionacademica')),
                ('id_persona_alta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona_tarea_alta', to='accounts.persona')),
                ('id_persona_finalizacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona_tarea_finalizacion', to='accounts.persona')),
                ('id_persona_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona_tarea_responsalbe', to='accounts.persona')),
                ('id_tipo_tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarea_tipo', to='calendarapp.tipotarea')),
                ('id_tutoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarea_tutoria', to='calendarapp.tutoria')),
            ],
            options={
                'verbose_name_plural': 'Tareas',
            },
        ),
    ]
