# Generated by Django 3.2.14 on 2023-05-16 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230421_1454'),
        ('calendarapp', '0007_motivo_id_tipo_orientacion_academica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id_persona_receptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona_receptor', to='accounts.persona'),
        ),
        migrations.AlterField(
            model_name='event',
            name='nro_curso',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='observacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
