# Generated by Django 3.2.14 on 2023-09-14 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0009_tarea_id_persona_ultima_modificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('iniciar_cita', 'Iniciar cita'), ('finalizar_cita', 'Finalizar cita'), ('editar_cita', 'Editar cita'), ('cancelar_cita', 'Cancelar cita'), ('confirmar_cita', 'Confirmar cita'), ('registrar_cita', 'registar cita'), ('editar_actividad_academica', 'Editar Actividad Academica'), ('registrar_actividad_academica', 'Registrar Actividad Academica'), ('cancelar_actividad_academica', 'Cancelar Actividad Academica')], 'verbose_name_plural': 'Actividades Academicas'},
        ),
    ]
