# Generated by Django 3.2.14 on 2023-10-10 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Success', 'success'), ('Info', 'info'), ('Wrong', 'wrong')], default='Info', max_length=20)),
                ('tipo', models.CharField(choices=[('tutoria', 'Tutoria'), ('orientacion', 'Orientacion'), ('cita_orientacion', 'Cita Orientacion'), ('cita_tutoria', 'Cita Tutoria'), ('tarea_tutoria', 'Tarea Tutoria'), ('tarea_orientacion', 'Tarea Orientacion'), ('tarea_cita_tutoria', 'Tarea Cita Tutoria'), ('tarea_cita_orientacion', 'Tarea Cita Orientacion')], default='tutoria', max_length=25)),
                ('id_tipo', models.IntegerField()),
                ('object_id_actor', models.PositiveIntegerField()),
                ('verbo', models.CharField(max_length=220)),
                ('read', models.BooleanField(default=False)),
                ('publico', models.BooleanField(default=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificar_actor', to='contenttypes.contenttype')),
                ('destiny', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
