# Generated by Django 3.2.14 on 2023-09-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='id_tipo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='tipo',
            field=models.CharField(choices=[('tutoria', 'Tutoria'), ('orientacion', 'Orientacion'), ('cita_orientacion', 'Cita Orientacion'), ('cita_tutoria', 'Cita Tutoria'), ('tarea_tutoria', 'Tarea Tutoria'), ('tarea_orientacion', 'Tarea Orientacion'), ('tarea_cita_tutoria', 'Tarea Cita Tutoria'), ('tarea_cita_orientacion', 'Tarea Cita Orientacion')], default='tutoria', max_length=25),
        ),
    ]
