# Generated by Django 3.2.14 on 2023-09-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_auto_20230905_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id_tipo',
            field=models.IntegerField(),
        ),
    ]
